### ISSUE TITLE
Внимание!!! Используем везде Ubuntu 18.04.5

### ISSUE THREAD

**Issue by alexvamp** [vasyakrg/rancher-ceph#3]
Добрый день. 
Первым делом хочу сказать большое спасибо. Крайне полезный урок получился. 
Можно узнать почему строго на 18.04.5 ?
да 20ке не запустится ?

**Comment by vasyakrg** [comment]
добрый.
нет. цеф не запустится.

я все собираюсь перепилить репу под новые реалии, но тогда и видео придется перезаписывать.
а очень не охота уже.
я планирую большой курс в этом году по кубу - там все это будет точно.
детальнее новости можно [тут](https://realmanual.ru) подсматривать
